# Generated by Django 5.0.2 on 2024-02-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id_book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id_to',
            field=models.IntegerField(),
        ),
    ]
